# Copyright (c) 2023 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

identifier: holyiot18010
name: holyiot18010
type: mcu
arch: arm
ram: 256
flash: 1024
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - usb_device
  - ble